### ISSUE TITLE
AUTH0_KEYWORD_REPLACE_MAPPINGS not working for emailTemplates, database connections, email providers, and pages when using yaml; possibly more.

### ISSUE THREAD

**Issue by victoru** [auth0/auth0-deploy-cli#133]
I was first alerted to this issue due to errors when trying to push pages that exist under an environment named path. e.g. `./pages/##ENV##/email_verify.html`
```
pages:
  - name: login
    enabled: true
    html: "./pages/##ENV##/login.html"
  - name: password_reset
    enabled: true
    html: "./pages/##ENV##/password_reset.html"
```

```
2019-06-21T04:44:10.801Z - error: Problem running command import
2019-06-21T04:44:10.801Z - error: Problem deploying pages
```

after temporarily hardcoding those values, I ran into more errors:
```
2019-06-21T05:30:55.237Z - error: Problem creating connections {"name":"somewhere-com"}
APIError: {"statusCode":400,"error":"Bad Request","message":"\"##GOOGLE_APPS_CLIENT_ID##\" is not a valid google oauth 2 client id, verify it in your Google API Console","errorCode":"invalid_body"}
```

this error only occurs because the values were invalid for that connection, I soon discovered other configuration was pushed successfully with unprocessed keyword mappings.
