### ISSUE TITLE
Can't update client with "client_credentials" grant

### ISSUE THREAD

**Issue by lorenh** [auth0/auth0-deploy-cli#205]
### Description

I keep getting this error when importing a client with client_credentials grant type

**Bad Request: Invalid grant types: client_credentials**

### Reproduction

When importing a client it always stops on the first client that contains client_credentials

a0deploy import -c config-dev.json -i tenant.yaml

```
2020-02-04T03:20:02.419Z - error: Problem running command import during stage processChanges when processing type clients
2020-02-04T03:20:02.420Z - error: Problem updating clients {"name":"Auth0 Management API (Test Client)","client_id":"ZeJ8dS0wLmhhrRZqKZ00JJTHIOwlu3nV"}
Bad Request: Invalid grant types: client_credentials
```

The Clients that are refusing to import all look similar to this (using YAML format):

```
  - name: Auth0 Management API (Test Client)
    allowed_clients: []
    allowed_logout_urls: []
    allowed_origins: []
    app_type: native
    callbacks: []
    cross_origin_auth: false
    custom_login_page_on: true
    description: Test client for Auth0 Management API.
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
      - client_credentials     <========= barfs on this ========
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    logo_uri: ''
    oidc_conformant: true
    sso: true
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins: []
```

### Environment

version 4.0.0
