### ISSUE TITLE
Update all database-connections scripts

### ISSUE THREAD

**Issue by felipeplets** [auth0/auth0-deploy-cli#248]
I'm looking for a way to use auth0-deploy-cli to actually update all existing database-connections scripts without having to have one directory for each database. 

Current solution: 

`database-connections/users/get_user.js` will update get_user.js for the database-connection users. 

Ideal solution: 

`database-connections/get_user.js` will update get_user.js for all existing database-connections in my Auth0 tenant.

**Comment by jtsampson** [comment]
@felipeplets 

**Workaround:**

Although I'm sure you've considered it...you could just use a CI pipeline copy the 'global' script to  to all connection sub-directories before running auth0-conf-cli. Use .gitignore to avoid checking it in if you run it locally (like with a script).

**Comment by felipeplets** [comment]
@jtsampson yes, I've considered, but in my case, the apps are created dynamically. So in order to do that I would have to access the Management API to get all the apps, then create the folders and move the global file to all the folders, what would be a bit painful and prone to error as those API calls are not synchronous. An internal option on Auth0 that does that would solve this all.

**Comment by willvedd** [comment]
@felipeplets You're correct that this isn't supported out-the-box but considering that all custom script properties are paths to the files, could you not just point to another directory?

```yaml
customScripts:
        get_user: ./databases/some-db-connection/get_user.js
        login: ./databases/some-db-connection/login.js
        verify: ./databases/some-db-connection/verify.js
```
could turn into:

```yaml
customScripts:
        get_user: ./databases/get_user.js
        login: ./databases/login.js
        verify: ./databases/verify.js
```

Would still require some level of manual configuration but technically satisfies the ask here. However, if you're asking for an automated, first-class support for this behavior, that is not possible and likely won't be supported anytime soon.
