### ISSUE TITLE
token_lifetime number validation not working during CLI deployment

### ISSUE THREAD

**Issue by hebra** [auth0/auth0-deploy-cli#325]
### Description

Due to a typo in one of our tenant configuration yaml files we found that the value for `token_lifetime` is not validated to be a valid integer.
```
- name: auth0-deploy-cli-extension
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 315I57600
      idle_token_lifetime: 2592000
```
As you can see the value for `token_lifetime` contains a capital `I` - but still during deploy using the CLI tool no validation error is thrown.

### Reproduction

1. Export a tenant configuration using this tool
2. Find e.g. the `auth0-deploy-cli-extension` app and in there the `token_lifetime` key
3. Add a capital `I` somewhere in the value (other letters might work as well)
4. Deploy the configuration to Auth0 using this CLI tool

### Environment

- **Version of this library used:** 5.5.1
- **Version of the platform or framework used, if applicable:** Node 12
