### ISSUE TITLE
Export does not respect variable substitutions from config.json

### ISSUE THREAD

**Issue by phillipuniverse** [auth0/auth0-deploy-cli#328]
### Description

> Provide a clear and concise description of the issue, including what you expected to happen.

I am using the YAML version of the deploy CLI with variables replaced from a config.json. Here is an example snippet of variable usage in `tenant.yaml`:

```yaml
...
resourceServers:
  - name: 'Shipwell ##ENVIRONMENT_NAME##'
     identifier: '##API_BASE_URL##'
```

I then have this `config.json`:

```json
{
  ...
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "ENVIRONMENT_NAME": "dev",
    "API_BASE_URL": "https://dev.myapp.com"
  }
}
```

When I export, variable data in `tenant.yaml` is overwritten with the real values. Example:

```bash
a0deploy dump --format yaml --output_folder . --config_file ./config.json
```

This modifies `tenant.yaml` with real values:

```yaml
...
resourceServers:
  - name: 'Shipwell dev'
     identifier: 'https://dev.myapp.com'
```

Preferably this would update my `config.json` with the real values being exported.

### Reproduction

Use environment variables in `tenant.yaml` or other files, these variables are incorrectly modified when exporting an Auth0 tenant.

### Environment

- **Version of this library used:** 5.5.3
- **Version of the platform or framework used, if applicable:** NPM 7.6.0, Node 15.11.0
- **Other relevant versions (language, server software, OS, browser):** OSX
- **Other modules/plugins/libraries that might be involved:**
