### ISSUE TITLE
Custom markdown for OTP email cannot be deployed

### ISSUE THREAD

**Issue by EeeasyBreezy** [auth0/auth0-deploy-cli#425]
### Description

Current implementation of auth0-deploy-cli does not import OTP email markdown for email connection
Instead, a path to file, which contains this markdown, is interpreted as markdown itself and imported into auth0 tenant

Expected: html markdown from corresponding file must be imported

### Reproduction

1. Export configuration in yaml format from Auth0 tenant
2. Set up email connection configuration  in yaml file with section below:
```
- name: email
      strategy: email
      is_domain_connection: false
      options:
          name: email
          totp:
              length: 6
              time_step: 180
          email:
              body: ./emails/otp.html
              from: <no-reply@xxx.com>
              syntax: liquid
              subject: Welcome to xxx
          disable_signup: true
          brute_force_protection: true
```
3. Make sure file `./emails/otp.html` exists and contains some valid html markup 
4. Invoke import operation using `auth0-deploy-cli` util
5. Go to auth0 management panel, open email connection and observe that instead of html mark up from `./emails/otp.html` `Body` field contains path to file from tenant config

### Environment

auth0-deploy-cli@7.3.7 is used
