### ISSUE TITLE
Using client_id/client_secret from client created by this tool, in this tool

### ISSUE THREAD

**Issue by thyming** [auth0/auth0-deploy-cli#582]
### Describe the problem you'd like to have solved

I would like to be able to use client id/client secret from a client I create with this tool as secret values in an Auth0 action (also created by this tool). Without this ability, these values have to be copied from the console after a run of the cli. 

### Describe the ideal solution

something like 
```yaml
secrets:
  - name: auth0_client_id
     value: &my_m2m_client.client_id
  - name: auth0_client_secret
     value: &my_m2m_client.client_secret
```

## Alternatives and current work-arounds

I may be mistaken, but the only alternative I see right now involves fetching the client details out of band of this tool, via the console or another api call, and injecting that as a variable into the config. 

### Additional context

No additional context.
