### ISSUE TITLE
Unable to apply dump with themes

### ISSUE THREAD

**Issue by lordgordon** [auth0/auth0-deploy-cli#602]
### Description

Applying a dumped tenant with `themes` results in error.

### Reproduction

After upgrading the command line from and old `7.5` version to the newest `7.14.1`, I executed the dump with 
```shell
a0deploy dump --export_ids=true --env -c config-qa.json -f yaml -o auth0-dump-qa;
```

and this config:
```json
{
  "AUTH0_DOMAIN": "***.auth0.com",
  "AUTH0_CLIENT_ID": "***",
  "AUTH0_ALLOW_DELETE": true,
  "EXCLUDED_PROPS": {
    "connections": [ "options.client_secret" ],
    "emailProvider": [ "credentials.smtp_pass" ]
  }
}
```

This dumped the `themes`. Now, when trying the apply command:
```shell
a0deploy import --env -c config-qa.json -i qa/tenant.yaml;
```

I have the following error
```
error: Problem running command import
error: Schema validation failed loading [
    {
        "keyword": "additionalProperties",
        "dataPath": ".themes[0]",
        "schemaPath": "#/properties/themes/items/additionalProperties",
        "params": {
            "additionalProperty": "themeId"
        },
        "message": "should NOT have additional properties"
    }
]
```

Here the  `themes` from my `tenant.yaml`:
```yaml
themes:
  - borders:
      button_border_weight: 1
      buttons_style: pill
      button_border_radius: 3
      input_border_weight: 1
      inputs_style: rounded
      input_border_radius: 3
      widget_corner_radius: 14
      widget_border_weight: 0
      show_widget_shadow: true
    colors:
      primary_button: '#F07F3C'
      primary_button_label: '#033243'
      secondary_button_border: '#c9cace'
      secondary_button_label: '#1e212a'
      base_focus_color: '#0076BF'
      base_hover_color: '#000000'
      links_focused_components: '#0076BF'
      header: '#033243'
      body_text: '#033243'
      widget_background: '#ffffff'
      widget_border: '#c9cace'
      input_labels_placeholders: '#65676e'
      input_filled_text: '#000000'
      input_border: '#c9cace'
      input_background: '#ffffff'
      icons: '#65676e'
      error: '#E83939'
      success: '#599A57'
    displayName: Unnamed Theme
    fonts:
      font_url: ''
      reference_text_size: 16
      title:
        bold: false
        size: 150
      subtitle:
        bold: false
        size: 87.5
      body_text:
        bold: false
        size: 87.5
      buttons_text:
        bold: false
        size: 100
      input_labels:
        bold: false
        size: 100
      links:
        bold: true
        size: 87.5
      links_style: normal
    page_background:
      page_layout: center
      background_color: '#F6F8F9'
      background_image_url: ''
    themeId: ***
    widget:
      logo_position: center
      logo_url: >-
        ***
      logo_height: 40
      header_text_alignment: center
      social_buttons_layout: bottom
```

### Environment

- Version of this library used: `7.14.1`
