### ISSUE TITLE
Applying a dumped passwordless email configuration with custom email template is not working

### ISSUE THREAD

**Issue by lordgordon** [auth0/auth0-deploy-cli#607]
### Description

After configuring the passwordless email flow from Auth0 Web UI, the deploy cli is unable to properly handle a custom email template.

### Reproduction

1. configure passwordless email: https://manage.auth0.com/dashboard/***/***/connections/passwordless
2. add a custom body and save
![image](https://user-images.githubusercontent.com/7745293/180222915-29dcd726-5217-4fa8-88b5-6472cc18b659.png)
3. run the dump `a0deploy dump --export_ids=true --env -c config-qa.json -f yaml -o auth0-dump-qa`
4. this adds the body in `./connections/email.html` (the html is correctly dumped) and the new settings (see below)
5. run apply `a0deploy import --env -c config-qa.json -i qa/tenant.yaml`
6. now from Auth0 UI the body is incorrectly overwritten: 
![image](https://user-images.githubusercontent.com/7745293/180224325-f5b4af91-9112-4872-815c-6d24cd103acc.png)
8. and the actual email is just the `./connections/email.html` text without my custom template and login url

Both `dump` and `apply` run without errors or warnings.

Here my current `config.json`:
```json
{
  "AUTH0_DOMAIN": "***.auth0.com",
  "AUTH0_CLIENT_ID": "***",
  "AUTH0_ALLOW_DELETE": true,
  "EXCLUDED_PROPS": {
    "connections": ["options.client_secret"],
    "emailProvider": ["credentials.smtp_pass"]
  },
  "AUTH0_EXCLUDED": ["themes"]
}

```

Here the relevant diff of the new sections added by the dump for the passwordless settings:
```yaml
connections:
 - name: email
    strategy: email
    id: ***
    enabled_clients:
      - my-app
    is_domain_connection: false
    options:
      name: email
      totp:
        length: 6
        time_step: 900
      email:
        body: ./email.html
        from: MyApp <login@myappcom>
        syntax: liquid
        subject: Welcome in MyApp!
      disable_signup: false
      brute_force_protection: true
```

### Environment

- auth0-deploy-cli version: `7.14.1`

**Comment by lordgordon** [comment]
I tried to workaround this by adding `"options.email.body"` to `EXCLUDED_PROPS` for `connections`:

```json
{
  "AUTH0_DOMAIN": "***",
  "AUTH0_CLIENT_ID": "***",
  "AUTH0_ALLOW_DELETE": true,
  "EXCLUDED_PROPS": {
    "connections": ["options.client_secret", "options.email.body"],
    "emailProvider": ["credentials.smtp_pass"]
  },
  "AUTH0_EXCLUDED": ["themes"]
}
```

This seems to dump the HTML, as wanted, and the new settings seems to ignore the body:
```yaml
email:
  from: MyApp <login@myapp.com>
  syntax: liquid
  subject: Benvenuto in MyApp!
```

Unfortunately, applying this overwrites all `email` settings:
![image](https://user-images.githubusercontent.com/7745293/180228009-fe37d6ab-57c0-40c7-a73a-fe159ed2ad6f.png)

**Comment by willvedd** [comment]
Thanks for reporting this. I suspect what happened here is that you unintentionally applied a set of configuration where the email template was absent. Looking at the command samples you've provided, you dumped to the `auth0-dump-qa` directory, but then deploy the `qa/tenant.yaml` file. I'm able to confirm this myself by being able to successfully apply passwordless email template changes under normal circumstances, but if I remove that template, I get the same `./email.html` string submitted into the body. 

The real bummer here is that the way that the Managment API works with connections, the `options` object isn't patched, instead the whole object gets replaced. Meaning, if we omit the email template configurations upon an absent email template, all that configuration will get wiped away. 

While the cause of this was likely accidental, we should be preventing accidentally destructive actions from occurring. My suggestion here is to throw an error if the template cannot be found. Do you believe that to be an acceptable approach here? Ideally, this validation would occur before the processing stage, but currently don't have a mechanism in place to facilitate that.

**Comment by willvedd** [comment]
> Yet, even after that I'm still unable to properly reapply the dumped changes. There is a way to have my apply working as expected?

This is certainly unusual and I'm not sure exactly what the issue is. I might recommend updating the body of the template through the UI as a one-off remediation, followed by an export to smooth over any odd issues that may be leftover.

Otherwise, I'm considering this fixed as we released code that detects and halts the deploy process during this exact situation in [7.14.2](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.14.2). Appreciate you bringing this to our attention!

**Comment by lordgordon** [comment]
> > Yet, even after that I'm still unable to properly reapply the dumped changes. There is a way to have my apply working as expected?
> 
> This is certainly unusual and I'm not sure exactly what the issue is. I might recommend updating the body of the template through the UI as a one-off remediation, followed by an export to smooth over any odd issues that may be leftover.
> 
> Otherwise, I'm considering this fixed as we released code that detects and halts the deploy process during this exact situation in [7.14.2](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.14.2). Appreciate you bringing this to our attention!

Got it! While the connection's settings is:
```yaml
connections:
 - name: email
    ...
    options:
      name: email
      ...
      email:
        body: ./email.html
```

I need to have `email.html` in the `qa/connections/email.html` path. Now it works. This is now clear thanks to the new error added with [7.14.2](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.14.2):
```
applying qa configuration
7.14.2
2022-08-02T15:20:00.947Z - error: Passwordless email template purportedly located at qa/connections/email.html does not exist for connection. Ensure the existence of this file to proceed with deployment.
2022-08-02T15:20:00.983Z - error: Problem running command import
2022-08-02T15:20:00.983Z - error: Problem deploying connections
```
