### ISSUE TITLE
Unable to provide arrays as environment variables for keyword replace mappings

### ISSUE THREAD

**Issue by wouterSeyen** [auth0/auth0-deploy-cli#687]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When providing a JSON serialized array as environment variable to the auth0-deploy-cli tool an error is thrown stating an array is expected. E.g.:
```
 error: Schema validation failed loading [
    {
        "keyword": "type",
        "dataPath": ".resourceServers[0].scopes",
        "schemaPath": "#/properties/resourceServers/items/properties/scopes/type",
        "params": {
            "type": "array"
        },
        "message": "should be array"
    }
]
```

### Expectation

It is possible to set JSON serialized arrays (of non-primitive objects) as environment variables and have them merged into the AUTH0_KEYWORD_REPLACE_MAPPINGS as an array (of non-primitive objects)

### Reproduction

1. Set a JSON serialized string as environment variable:
``export API_SCOPES='[{"value":"my_scope","description":"A custom scope"},{"value":"my_second_scope","description":"Another custom scope"}]'``
2. Configure the tenant.yaml to use the environment variable:
```
resourceServers:
  - name: My API
    identifier: https://my.api.com
    allow_offline_access: false
    scopes: @@API_SCOPES@@
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_lifetime: 86400
    token_lifetime_for_web: 7200
```
3. Run an import using the auth0-deploy-cli tool

### Deploy CLI version

7.15.1

### Node version

16.17.0
