### ISSUE TITLE
Dumping config overwrites literal value in `tenant.yaml` with erroneous keyword

### ISSUE THREAD

**Issue by DevinRiley** [auth0/auth0-deploy-cli#826]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When dumping tenant config to a local tenant.yaml file, the dump clobbers a literal value in my config with a keyword intended to be used by another field. Here is the literal example of what's happening, with actual `client_id` values scrubbed.

### Before
Excerpt of `tenant.yaml`
```yaml
clientGrants:
  - client_id: API Explorer Application
    audience: https://##TENANT##.us.auth0.com/api/v2/
    scope: '@@API_EXPLORER_APPLICATION_CLIENT_GRANT_SCOPES@@'
  - client_id: M2M Application
    audience: '##API_IDENTIFIER##'
    scope: []
  - client_id: M2M Application
    audience: https://##TENANT##.us.auth0.com/api/v2/
    scope:
      - create:users
```

### Run Auth0 deploy CLI command
```bash
$ a0deploy dump -c=config-dev.json --format=yaml --output_folder=resources
```

### After
Excerpt of `tenant.yaml`
```yaml
clientGrants:
  - client_id: API Explorer Application
    audience: https://##TENANT##.us.auth0.com/api/v2/
    scope: '@@API_EXPLORER_APPLICATION_CLIENT_GRANT_SCOPES@@'
  - client_id: M2M Application
    audience: '##API_IDENTIFIER##'
    scope: []
  - client_id: M2M Application
    audience: https://##TENANT##.us.auth0.com/api/v2/
    scope: '@@API_EXPLORER_APPLICATION_CLIENT_GRANT_SCOPES@@'
```

Note that the `scope` of the the second M2M Application grant gets overridden.

### Expectation

I'd expect the literal value of the client scope to be maintained (I wouldn't expect a config dump to modify this portion of the `tenant.yaml` file)

Note that this is potentially hazardous if not caught by a user, since it is could unintentionally escalate the scope depending on what values the keyword holds.

### Reproduction

I haven't attempted reproduction of this outside of tenants I actually use, but can put some effort towards this if you need help reproducing it. Hopefully the description above is enough to reproduce in a fresh tenant.

### Deploy CLI version

7.18.0

### Node version

v14.19.3
