### ISSUE TITLE
Exporting email provider fails (exports only default values)

### ISSUE THREAD

**Issue by hjdarnel** [auth0/auth0-deploy-cli#84]
Hi all, 

I see that with the version 2 email templates and email providers are supported in this cli - this is awesome! My team is having trouble exporting email providers:

Running either of the following: 
```bash 
a0deploy export -f yaml -c ./tenants/stage/stageConfig.json -o ./tenants/stage/

a0deploy export -f directory -c ./tenants/stage/stageConfig.json -o ./tenants/stage/
```

results in a provider block like this:
``` yml
// provider.json
{
  "name": "smtp",
  "enabled": true,
  "credentials": {
    "smtp_host": "your.smtp.host.com",
    "smtp_port": 25,
    "smtp_user": "YOUR_SMTP_USER",
    "smtp_pass": "YOUR_SMTP_PASS"
  }
}
```

My team certainly has a custom provider setup, and those aren't the username/password. Is there a permissions problem here that I'm missing? Or is there something else here that's my fault?

Thanks in advance 😃
