### ISSUE TITLE
Authentication profile is not set correctly

### ISSUE THREAD

**Issue by madsjk816** [auth0/auth0-deploy-cli#842]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Since upgrading the auth0-deploy-cli tool from version 7.17.5 to the latest version 7.19.0 the 'Authentication Profile' setting is not being correctly deployed.

When deploying using version 7.17.5 the 'Authentication Profile' setting regarding identifier first is respected and set correctly, however, when deploying using version 7.19.0 the 'Authentication Profile' seems to be set to 'Identifier + password' which is quite unfortunate when you rely on password-less logins.

I've tried back and forth to slim down the `tenant.yaml` file to see what might cause the conflict, and it seems that the 'branding' part of it causes the issue to appear. If i remove the `branding` part of the .yaml file the 'Authentication Profile' is set to 'identifier-first' using both versions of the cli-tool

### Expectation

When using the following setting in the `tenant.yaml` file
```
prompts:
  identifier_first: true
```

Identifier first is set as the authentication profile. If it is not possible due to conflicting settings would expect the tool to either throw a warning or an error.

### Reproduction

A .yaml file with the following contents:

```
branding:
  logo_url: >-
    https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Logo_de_Auth0.svg/800px-Logo_de_Auth0.svg.png?20211214133710
prompts:
  identifier_first: true
  universal_login_experience: new
```
run `npm install -g auth0-deploy-cli@7.17.5`

'Identifier First' should be respected when using this version.

Next up:

run `npm install -g auth0-deploy-cli@7.19.0`

The authentication profile is now set to 'Identifier + password'

Do the same procedure with the following contents in the `tenant.yaml` file instead:

```
prompts:
  identifier_first: true
  universal_login_experience: new
```

The 'identifier first' authentication profile is now set correctly using both versions of the cli-tool.

### Deploy CLI version

7.19.0

### Node version

16.14.2

**Comment by madsjk816** [comment]
Hi Auth0,

Any updates on this issue?

**Comment by danielmalmros** [comment]
Any updates?

**Comment by willvedd** [comment]
I'm unable to replicate the difference in behavior between v7.17.5 and current. However, I believe this can be resolved by configuring the `webauthn_platform_first_factor` property in addition to `identifier_first`. See below to see how to achieve each configuration profile:

**Identifier + Password**
```yaml
prompts:
  identifier_first: false
  webauthn_platform_first_factor: false
```

**Identifier First**
```yaml
prompts:
  identifier_first: true
  webauthn_platform_first_factor: false
```

**Identifier First + Biometrics**
```yaml
prompts:
  identifier_first: true
  webauthn_platform_first_factor: true
```

Please advise wether or not this resolves your issue.

**Comment by willvedd** [comment]
All - I'm considering this issue resolved. Please re-open if you're still unable to achieve the desired configuration profile.

**Comment by victornvg** [comment]
@willvedd I got the same issue for this, here is my setup in `tenant.yaml` file
```
prompts:
  identifier_first: true
  universal_login_experience: new
  webauthn_platform_first_factor: false
```
When I execute the command `a0deploy import --input_file tenant.yaml --config_file .config.json --debug`, I do not see any log entries related to prompts.
Additionally, the `Authentication Profile` does not change to `Identifier First`.

I’m using auth0-deploy-cli version v7.24.0 and node version v20.14.0
