### ISSUE TITLE
Keyword preservation fails for client grants

### ISSUE THREAD

**Issue by DevinRiley** [auth0/auth0-deploy-cli#855]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When I dump config to my `tenant.yml` file, it doesn't preserve keywords for my client grants. This appears to be related to [this PR](https://github.com/auth0/auth0-deploy-cli/pull/837) based on the caveat made in that PR description and my own testing between versions `7.18.0` and `7.19.0` 

### Before:

```yaml
clientGrants:
  - client_id: API Explorer Application
    audience: https://##TENANT##.us.auth0.com/api/v2/
    scope: '@@API_EXPLORER_APPLICATION_CLIENT_GRANT_SCOPES@@'
  - client_id: M2M Application
    audience: '##API_IDENTIFIER##'
    scope: []
  - client_id: M2M Application
    audience: https://##TENANT##.us.auth0.com/api/v2/
    scope:
      - create:users
```

### Run `a0deploy dump -c=config-dev.json --format=yaml --output_folder=resources`

After:
```yaml
clientGrants:
  - client_id: API Explorer Application
    audience: https://redacted.us.auth0.com/api/v2/
    scope:
      - read:users
      - update:users
      - delete:users
      - create:users
  - client_id: M2M application
    audience: http://localhost:3000
    scope: []
  - client_id: Entity Management M2M
    audience: https://redacted.us.auth0.com/api/v2/
    scope:
      - create:users
```

This is a problem for us because we deploy this tenant yaml to different environments and need the keyword replacements to work for each environment.

### Expectation

I'd expect keywords to be preserved in the `tenant.yml` file.

### Reproduction

I have only encountered this on my actual tenant, but I believe you could reproduce by settings up multiple client grants that use the same `client_id`

### Deploy CLI version

7.19.0

### Node version

14.19.3
