### ISSUE TITLE
Azure EventGrid Log Stream creation fails

### ISSUE THREAD

**Issue by BavoLuysterborg** [auth0/auth0-deploy-cli#875]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When importing a previously exported Log Stream configuration into a different tenant, the create Log Stream operation fails with error:
> Bad Request: Payload validation error: 'Data does not match any schemas from 'oneOf''.

Removing the `sink.azurePartnerTopic` property from the Log Stream config fixes this error.

### Expectation

The `sink.azurePartnerTopic` property should be exported, however, during import, this property should be excluded from the object when performing a create operation.

### Reproduction

1. Export a tenant config containing a Log Stream pointing to an EventGrid sink, the resulting LogStreams section will be:
```yaml
logStreams:
  - name: Azure Event Grid
    filters:
      - type: category
        name: auth.token_exchange.fail
      - ...
    sink:
      azureSubscriptionId: <subscription id>
      azureRegion: <region>
      azureResourceGroup: <resource group>
      azurePartnerTopic: <partner topic name>
    status: active
    type: eventgrid
```
2. Import the config into a different tenant that does not already have this EventGrid Log Stream set-up
3. The create API call will fail with the following message:
> Bad Request: Payload validation error: 'Data does not match any schemas from 'oneOf''.

### Deploy CLI version

7.20.0

### Node version

20.6.1
