### ISSUE TITLE
Application callback URLs encoding problem

### ISSUE THREAD

**Issue by nilobarp** [auth0/auth0-deploy-cli#88]
When I deploy the following application

```yaml
clients:
  - name: 'MyApp'
    app_type: 'spa'
    oidc_conformant: true
    is_first_party: true
    callbacks:
      - '##MYAPP_CALLBACK_URLS##'
    jwt_configuration:
      alg: 'RS256'
      lifetime_in_seconds: 36000
      secret_encoded: false
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
```
with MYAPP_CALLBACK_URLS set to 

```sh
MYAPP_CALLBACK_URLS=http://localhost:3000/authenticated, http://localhost:3080/authenticated
```
Auth0 complains that callback URL is not listed in the app. When I open the app settings and manually delete and re-add the spaces everything works. Visually there's no difference but certainly the spaces are not what they appear to be.
