### ISSUE TITLE
Forms support

### ISSUE THREAD

**Issue by joshbalfour** [auth0/auth0-deploy-cli#904]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

It would be amazing if the deploy CLI supported Forms.

### Describe the ideal solution

```yaml
forms:
  - name: "form name"
     form: "./form.json"
```

Where form.json is what's exportable/importable from the editor.

### Alternatives and current workarounds

Right now we're having to import them manually using the editor.
