### ISSUE TITLE
Should import customDomains appear in log?

### ISSUE THREAD

**Issue by christianblust** [auth0/auth0-deploy-cli#994]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi all,

I work with the auth0 deploy cli and recently added a custom domain to our tenants. I configured them on the dashboard, exported the dev tenant, added the `customDomains` part to our tenants and configured them via environment configs.

```
customDomains:
  - domain: '##CUSTOM_DOMAIN##'
    primary: true
    status: ready
    tls_policy: recommended
    type: auth0_managed_certs
    verification:
      methods:
        - name: CNAME
          record: '##CUSTOM_DOMAIN_CNAME_RECORD##'
          domain: '##CUSTOM_DOMAIN##'
```

I noticed that in the import log all resources defined in the tenant.yaml appear with a log statement like `"2024-12-03T12:56:21.791Z - info: Updated [actions]: {"id":"ididididid","name":"mfa exceptions"}`". Those resources were not modified, so I thought that it is just updating everything according to the current tenant configuration.

However i can not see anything related to the custom domain - is this to be expected? I just want to make sure that my configuration is correct and I could not find any documentation about this. 

Best
Chris

### Expectation

Log statement if really everything should be logged? If not, maybe a short documentation. 

### Reproduction

1. Add customDomains to tenant.yaml
```
customDomains:
  - domain: '##CUSTOM_DOMAIN##'
    primary: true
    status: ready
    tls_policy: recommended
    type: auth0_managed_certs
    verification:
      methods:
        - name: CNAME
          record: '##CUSTOM_DOMAIN_CNAME_RECORD##'
          domain: '##CUSTOM_DOMAIN##'
```

2. Run import
3. Verify Log Statements

### Deploy CLI version

8.3.0

### Node version

20.18.0
